### ISSUE TITLE
Update config format

### ISSUE THREAD

**Issue by NoUseFreak** [NoUseFreak/wait-for-it#2]
```
services:
  mysql_check:
    plugin: mysql
    timeout: 30
    delay: 5
    frequency: 1
    parameters:
      host: localhost
      port: 3306
      username: root
      password: root
```
